// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import('./components/icons/avatar.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    FolderDetail: typeof import('./components/FolderDetail.vue')['default']
    FolderForm: typeof import('./components/FolderForm.vue')['default']
    FolderTree: typeof import('./components/FolderTree.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    FormEl: typeof import('./components/form-el.vue')['default']
    FormSignup: typeof import('./components/form-signup.vue')['default']
    PlusButton: typeof import('./components/icons/PlusButton.vue')['default']
    README: typeof import('./components/README.md')['default']
    RemoveButton: typeof import('./components/icons/RemoveButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
